# https://www.dartlang.org/guides/language/analysis-options
analyzer:
    errors:
        unused_local_variable: ignore
        unused_field: ignore
        deprecated_member_use: ignore
        todo: ignore
