///
//  Generated code. Do not modify.
//  source: const.proto
///
// ignore_for_file: non_constant_identifier_names,library_prefixes,unused_import

const EntityType$json = const {
  '1': 'EntityType',
  '2': const [
    const {'1': 'EntityDevice', '2': 0},
    const {'1': 'EntityScene', '2': 1},
    const {'1': 'EntityArea', '2': 2},
    const {'1': 'EntityBinding', '2': 3},
    const {'1': 'EntitySystem', '2': 4},
    const {'1': 'EntityFirmware', '2': 5},
    const {'1': 'EntityAutomation', '2': 6},
    const {'1': 'EntityAutomationSet', '2': 7},
  ],
};

const AttributeID$json = const {
  '1': 'AttributeID',
  '2': const [
    const {'1': 'AttrIDOnOffStatus', '2': 0},
    const {'1': 'AttrIDTotalPower', '2': 1},
    const {'1': 'AttrIDActivePower', '2': 2},
    const {'1': 'AttrIDInsertExtractStatus', '2': 3},
    const {'1': 'AttrIDOccupancy', '2': 4},
    const {'1': 'AttrIDLuminance', '2': 5},
    const {'1': 'AttrIDTemperature', '2': 6},
    const {'1': 'AttrIDBinInputStatus', '2': 7},
    const {'1': 'AttrIDBatteryPercent', '2': 8},
    const {'1': 'AttrIDFirmwareVersion', '2': 9},
    const {'1': 'AttrIDZBPermitJoin', '2': 10},
    const {'1': 'AttrIDWindowCoveringDirection', '2': 11},
    const {'1': 'AttrIDWindowTargetLiftPercent', '2': 12},
    const {'1': 'AttrIDWindowCurrentLiftPercent', '2': 13},
    const {'1': 'AttrIDSupportOTA', '2': 14},
    const {'1': 'AttrIDAlertLevel', '2': 15},
    const {'1': 'AttrIDWindowCoveringMotorStatus', '2': 16},
    const {'1': 'AttrIDWindowCoveringMotorTripConfigured', '2': 17},
    const {'1': 'AttrIDWindowCoveringUserType', '2': 18},
    const {'1': 'AttrIDWindowCoveringMotorTripAdjusting', '2': 19},
    const {'1': 'AttrIDEntityIsNew', '2': 20},
    const {'1': 'AttrIDDeviceJoinedTime', '2': 21},
    const {'1': 'AttrIDDeviceConnectedTime', '2': 22},
    const {'1': 'AttrIDOccupancyLeft', '2': 23},
    const {'1': 'AttrIDOccupancyRight', '2': 24},
    const {'1': 'AttrIDCfgIndicatorLED', '2': 25},
    const {'1': 'AttrIDCfgDisableRelay', '2': 26},
    const {'1': 'AttrIDCfgButtonBindingType', '2': 27},
    const {'1': 'AttrIDCfgLEDIllumThreshold', '2': 28},
    const {'1': 'AttrIDFirmwareUpgradingVersion', '2': 29},
    const {'1': 'AttrIDFirmwareUpgradingPercent', '2': 30},
    const {'1': 'AttrIDEnableKeepOnOffStatus', '2': 31},
    const {'1': 'AttrIDFirmwareRecommandVersion', '2': 32},
    const {'1': 'AttrIDLastKnobAngle', '2': 33},
    const {'1': 'AttrIDLastKnobUsedMS', '2': 34},
    const {'1': 'AttrIDAutoEnabled', '2': 35},
    const {'1': 'AttrIDAutoRenderType', '2': 36},
    const {'1': 'AttrIDAutoSetID', '2': 37},
    const {'1': 'AttrIDCFGSWPureInput', '2': 38},
    const {'1': 'AttrIDCFGSWInputMode', '2': 39},
    const {'1': 'AttrIDCFGSWPolarity', '2': 40},
    const {'1': 'AttrIDCFGButtonLEDStatus', '2': 41},
    const {'1': 'AttrIDAutoVersion', '2': 42},
    const {'1': 'AttrIDLCTargetLevel', '2': 43},
    const {'1': 'AttrIDLCCurrentLevel', '2': 44},
    const {'1': 'AttrIDDisabledRelayStatus', '2': 45},
    const {'1': 'AttrIDNumOfTimeoutControls', '2': 46},
    const {'1': 'AttrIDZHHIsOnline', '2': 47},
    const {'1': 'AttrIDZHHIsRunning', '2': 48},
    const {'1': 'AttrIDACTargetTemperature', '2': 49},
    const {'1': 'AttrIDACCurrentTemperature', '2': 50},
    const {'1': 'AttrIDACFanSpeed', '2': 51},
    const {'1': 'AttrIDACWorkMode', '2': 52},
    const {'1': 'AttrIDZHHErrorCode', '2': 53},
    const {'1': 'AttrIDCFGMutexedIndex', '2': 54},
    const {'1': 'AttrIDCFGMutexedDelayMs', '2': 55},
    const {'1': 'AttrIDCFGButtonLEDPolarity', '2': 56},
    const {'1': 'AttrIDCFGLoopHasRelay', '2': 57},
    const {'1': 'AttrIDCFGSelfBindingID', '2': 58},
    const {'1': 'AttrIDAutoSetClass', '2': 59},
    const {'1': 'AttrIDWindowCoveringMotorType', '2': 60},
    const {'1': 'AttrIDColorTemperature', '2': 61},
    const {'1': 'AttrIDColorCurrentX', '2': 62},
    const {'1': 'AttrIDColorCurrentY', '2': 63},
    const {'1': 'AttrIDColorCIEYXY', '2': 64},
    const {'1': 'AttrIDColorCIERGB', '2': 65},
    const {'1': 'AttrIDZBChannel', '2': 66},
    const {'1': 'AttrIDCFGTurnOnOnly', '2': 67},
    const {'1': 'AttrIDCFGTurnOffDelayMs', '2': 68},
    const {'1': 'AttrIDCFGSwitchDirection', '2': 69},
    const {'1': 'AttrIDAutoTimerState', '2': 70},
    const {'1': 'AttrIDAutoTimerRemainedTimeMs', '2': 71},
    const {'1': 'AttrIDAutoExecState', '2': 72},
    const {'1': 'AttrIDDoorLockState', '2': 73},
    const {'1': 'AttrIDWindowConveringControlState', '2': 74},
    const {'1': 'AttrIDZBChannelUpdateState', '2': 75},
  ],
};

const DeviceProfile$json = const {
  '1': 'DeviceProfile',
  '2': const [
    const {'1': 'ProfilePIR', '2': 0},
    const {'1': 'SmartPlug', '2': 1},
    const {'1': 'OnOffLight', '2': 2},
    const {'1': 'DoorContact', '2': 3},
    const {'1': 'OnOffSwitch', '2': 4},
    const {'1': 'WindowCovering', '2': 5},
    const {'1': 'YanButton', '2': 6},
    const {'1': 'SmartDial', '2': 7},
    const {'1': 'ColorLight', '2': 8},
    const {'1': 'HAZHHGateway', '2': 9},
    const {'1': 'HAZHHUnitMachine', '2': 10},
    const {'1': 'HADoorLock', '2': 11},
    const {'1': 'ZLLExtendedColorLight', '2': 12},
    const {'1': 'ZLLColorTemperatureLight', '2': 13},
  ],
};

const BindingType$json = const {
  '1': 'BindingType',
  '2': const [
    const {'1': 'Invalid', '2': 0},
    const {'1': 'Keypress', '2': 1},
    const {'1': 'OpenClose', '2': 2},
    const {'1': 'PIR', '2': 3},
    const {'1': 'SmartDialBinding', '2': 4},
  ],
};

const SceneStage$json = const {
  '1': 'SceneStage',
  '2': const [
    const {'1': 'INVALIDSTAGE', '2': 0},
    const {'1': 'SceneStarted', '2': 1},
    const {'1': 'SceneFinished', '2': 2},
  ],
};

const ActionStage$json = const {
  '1': 'ActionStage',
  '2': const [
    const {'1': 'ActionStarted', '2': 0},
    const {'1': 'ActionFinsihed', '2': 1},
  ],
};

const OnOffCommand$json = const {
  '1': 'OnOffCommand',
  '2': const [
    const {'1': 'Off', '2': 0},
    const {'1': 'On', '2': 1},
    const {'1': 'Toggle', '2': 2},
  ],
};

const WindowCoveringMotorStatus$json = const {
  '1': 'WindowCoveringMotorStatus',
  '2': const [
    const {'1': 'Quiet', '2': 0},
    const {'1': 'Opening', '2': 1},
    const {'1': 'Closing', '2': 2},
    const {'1': 'Setting', '2': 3},
    const {'1': 'Hijacked', '2': 4},
  ],
};

const WindowCoveringUserType$json = const {
  '1': 'WindowCoveringUserType',
  '2': const [
    const {'1': 'TypeLeft', '2': 0},
    const {'1': 'TypeRight', '2': 1},
    const {'1': 'TypeBoth', '2': 2},
  ],
};

const WindowCoveringTripConfigured$json = const {
  '1': 'WindowCoveringTripConfigured',
  '2': const [
    const {'1': 'Unconfigured', '2': 0},
    const {'1': 'Configured', '2': 1},
    const {'1': 'UnknownStatus', '2': -1},
  ],
};

const WindowCoveringMotorDirection$json = const {
  '1': 'WindowCoveringMotorDirection',
  '2': const [
    const {'1': 'DirDefault', '2': 0},
    const {'1': 'DirReverse', '2': 1},
    const {'1': 'DirUnknown', '2': 2},
  ],
};

const AssociationAction$json = const {
  '1': 'AssociationAction',
  '2': const [
    const {'1': 'ActionShare', '2': 0},
    const {'1': 'ActionRequest', '2': 1},
    const {'1': 'ActionAccept', '2': 2},
    const {'1': 'ActionDecline', '2': 3},
    const {'1': 'ActionApprove', '2': 4},
    const {'1': 'ActionReject', '2': 5},
    const {'1': 'ActionCancelShare', '2': 6},
    const {'1': 'ActionCancelRequest', '2': 7},
    const {'1': 'ActionRemove', '2': 8},
  ],
};

const SubscriptionType$json = const {
  '1': 'SubscriptionType',
  '2': const [
    const {'1': 'Unknown', '2': 0},
    const {'1': 'From', '2': 1},
    const {'1': 'To', '2': 2},
    const {'1': 'Both', '2': 3},
  ],
};

const ErrorCode$json = const {
  '1': 'ErrorCode',
  '2': const [
    const {'1': 'EC_OK', '2': 0},
    const {'1': 'EC_BADREQUEST', '2': -1},
    const {'1': 'EC_INVALIDRESPONSE', '2': -2},
    const {'1': 'EC_REQUEST_TIMEOUT', '2': 1},
    const {'1': 'EC_DEVICE_NOT_EXIST', '2': 2},
    const {'1': 'EC_SCENE_NOT_EXIST', '2': 3},
    const {'1': 'EC_SCENE_ALREADY_ON', '2': 4},
    const {'1': 'EC_INVALID_DEVICE_TYPE', '2': 5},
    const {'1': 'EC_INVALID_DEVICE_PROFILE', '2': 6},
    const {'1': 'EC_SCENE_ALREAY_EXIST', '2': 7},
    const {'1': 'EC_SCENE_NOT_TURNED_ON', '2': 8},
    const {'1': 'EC_SCENE_ALREADY_TURNED_ON', '2': 9},
    const {'1': 'EC_SCENE_ALREADY_TURNED_OFF', '2': 10},
    const {'1': 'EC_DEVICE_BINDING_TIMEOUT', '2': 11},
    const {'1': 'EC_BIND_INVALID_DEVICE', '2': 12},
    const {'1': 'EC_BINDING_ALREADY_EXIST', '2': 13},
    const {'1': 'EC_BINDING_NOT_EXIST', '2': 14},
    const {'1': 'EC_DELETE_NON_EXIST_BINDING', '2': 15},
    const {'1': 'EC_BINDING_UPDATE_SAME_SCENE', '2': 16},
    const {'1': 'EC_DEVICE_NOT_ONLINE', '2': 17},
    const {'1': 'EC_FAILED_PARSE_JSON_FILE', '2': 18},
    const {'1': 'EC_INVALID_SCENE_CONFIG_FILE', '2': 19},
    const {'1': 'EC_SCENE_EXEC_ALREADY_FINISHED', '2': 20},
    const {'1': 'EC_SCENE_EXEC_WAITING_FOR_ACK', '2': 21},
    const {'1': 'EC_SCENE_EXEC_TRIED_MAXMUM_TIMES', '2': 22},
    const {'1': 'EC_FAILED_OPEN_CONFIG_DIR', '2': 23},
    const {'1': 'EC_FAILED_FOPEN_FILE', '2': 24},
    const {'1': 'EC_DUPLICATE_AREA_NAME', '2': 25},
    const {'1': 'EC_RENAME_NON_EXISTED_AREA', '2': 26},
    const {'1': 'EC_DELETE_NON_EXISTED_AREA', '2': 27},
    const {'1': 'EC_AREA_NOT_EXIST', '2': 28},
    const {'1': 'EC_DUPLICATE_SCENE_NAME', '2': 29},
    const {'1': 'EC_DEVICE_ALREADY_ADDED', '2': 30},
    const {'1': 'EC_SET_SAME_ALERT_LEVEL', '2': 31},
    const {'1': 'EC_NO_DEVICE_ADDED', '2': 32},
    const {'1': 'EC_GLOBAL_SCENE_ON_RUNING', '2': 33},
    const {'1': 'EC_GLOBAL_SCENE_ALREADY_ON', '2': 34},
    const {'1': 'EC_TOGGLE_GLOBAL_SCENE', '2': 35},
    const {'1': 'EC_SCENE_UPDATE_INVALID_PARAMS', '2': 36},
    const {'1': 'EC_MISSED_PARAMETER', '2': 37},
    const {'1': 'EC_SCENE_IS_NULL', '2': 38},
    const {'1': 'EC_INVALID_PARAMETER', '2': 39},
    const {'1': 'EC_INVALID_COMMAND_PARAM', '2': 40},
    const {'1': 'EC_DEVICE_STATUS_ALREADY_SET', '2': 41},
    const {'1': 'EC_NO_NEED_EXEC_SCENE', '2': 42},
    const {'1': 'EC_NO_NEED_EXEC_ACTION', '2': 43},
    const {'1': 'EC_NO_ACTIONS', '2': 44},
    const {'1': 'EC_NO_VALID_ACTION', '2': 45},
    const {'1': 'EC_ACTION_PARTLY_VALID', '2': 46},
    const {'1': 'EC_INVALID_SCENE', '2': 47},
    const {'1': 'EC_INVALID_ADDRESS', '2': 48},
    const {'1': 'EC_SCENE_CONTAINS_NO_DEVICES', '2': 49},
    const {'1': 'EC_PERMIT_JOIN_ALREADY_DISABLED', '2': 50},
    const {'1': 'EC_PERMIT_JOIN_ALREADY_ENABLED', '2': 51},
    const {'1': 'EC_SAME_REQUEST_ALREADY_STARTED', '2': 52},
    const {'1': 'EC_SCENE_EXECUTION_ALREADY_STARTED', '2': 53},
    const {'1': 'EC_UNKNOWN_PUBSUB_NODE', '2': 54},
    const {'1': 'EC_BINDING_DUPLICATED', '2': 55},
    const {'1': 'EC_BINDING_ALREADY_ENABLED', '2': 56},
    const {'1': 'EC_ASH_RESET_FAILED', '2': 57},
    const {'1': 'EC_NO_ACTION_TO_RUN', '2': 58},
    const {'1': 'EC_SYSTEM_NOT_AVAILABLE', '2': 59},
    const {'1': 'EC_NCP_ERROR_FRAME', '2': 60},
    const {'1': 'EC_NCP_NOT_EXIST', '2': 61},
    const {'1': 'EC_UN_SUPPORTED', '2': 62},
    const {'1': 'EC_ENTITY_NOT_AVAILABLE', '2': 63},
    const {'1': 'EC_ENGINE_DISCONNECTED', '2': 64},
    const {'1': 'EC_FAILED_OPEN_IMAGES_DIR', '2': 65},
    const {'1': 'EC_UPGRADE_ALREADY_IN_PROGRESS', '2': 66},
    const {'1': 'EC_UPGRADE_FAIL_TO_LOCK', '2': 67},
    const {'1': 'EC_UPGRADE_PACKAGE_NOT_FOUND', '2': 68},
    const {'1': 'EC_UPGRADE_PACKAGE_CORRUPTED', '2': 69},
    const {'1': 'EC_UPGRADE_FAIL_TO_ENABLE_RECOVERY', '2': 70},
    const {'1': 'EC_INVALID_OTA_IMAGE_PATH', '2': 71},
    const {'1': 'EC_INVALID_OTA_IMAGE_DATA', '2': 72},
    const {'1': 'EC_SAME_OTA_IMAGE_ALREADY_LOADED', '2': 73},
    const {'1': 'EC_OTA_IMAGE_NOT_EXIST', '2': 74},
    const {'1': 'EC_FIRMWARE_NOT_EXIST', '2': 75},
    const {'1': 'EC_INVALID_OTA_IMAGE_TYPE', '2': 76},
    const {'1': 'EC_NO_DEVICE_MATCHED', '2': 77},
    const {'1': 'EC_OTA_TASK_ALREADY_RUNNING', '2': 78},
    const {'1': 'EC_NO_VALID_OTA_IMAGE', '2': 79},
    const {'1': 'EC_FEATURE_UNSUPPORTED', '2': 80},
    const {'1': 'EC_INCORRECT_FIRMWARE_VERSION', '2': 81},
    const {'1': 'EC_OTA_UPGRADE_END_STATUS_ERROR', '2': 82},
    const {'1': 'EC_OTA_UPGRADE_END_TYPE_ERROR', '2': 83},
    const {'1': 'EC_OTA_UPGRADE_END_MANU_CODE_ERROR', '2': 84},
    const {'1': 'EC_OTA_UPGRADE_END_VERSION_ERROR', '2': 85},
    const {'1': 'EC_OTA_UPGRADE_END_REMAINED_DATA', '2': 86},
    const {'1': 'EC_FEATURE_ATTRIBUTE_READ_ERROR', '2': 87},
    const {'1': 'EC_UNSUPPORTED_ATTR_KEY', '2': 88},
    const {'1': 'EC_ENDPOINT_NOT_EXIST', '2': 89},
    const {'1': 'EC_ENDPOINT_MISSED_ATTR', '2': 90},
    const {'1': 'EC_READ_ATTR_DATA_SIZE_TOO_BIG', '2': 91},
    const {'1': 'EC_READ_ATTR_RESPONSE_ERROR', '2': 92},
    const {'1': 'EC_OTA_IMAGE_DATA_DAMAGED', '2': 93},
    const {'1': 'EC_UNSUPPORTED_READ_ATTR_KEY', '2': 94},
    const {'1': 'EC_OTA_DEVICE_OFFLINE', '2': 95},
    const {'1': 'EC_ENTITY_NOT_EXIST', '2': 96},
    const {'1': 'EC_OTA_START_OFFLINE', '2': 97},
    const {'1': 'EC_DEVICE_UNAVAILABLE', '2': 98},
    const {'1': 'EC_ENTITY_NOT_DEVICE', '2': 99},
    const {'1': 'EC_ENTITY_ALREADY_DELETED', '2': 100},
    const {'1': 'EC_ENTITY_ALREADY_DELETING', '2': 101},
    const {'1': 'EC_DELETE_OFFLINE_DEVICE', '2': 102},
    const {'1': 'EC_TRIED_DELETE_MAX_TIMES', '2': 103},
    const {'1': 'EC_DELETE_ALREADY_SCHEDULED', '2': 104},
    const {'1': 'EC_ON_SCHEDULE_DELETE_TASK', '2': 105},
    const {'1': 'EC_ENTITY_UNDELETABLE_DEVICE', '2': 106},
    const {'1': 'EC_DEVICE_WITHOUT_ON_OFF_FEATURE', '2': 107},
    const {'1': 'EC_OTA_IMAGE_NOTIFY_RESPONE', '2': 108},
    const {'1': 'EC_SYSTEM_UNAVAILABLE', '2': 109},
    const {'1': 'EC_ZB_ENGINE_DISCONNECTED', '2': 110},
    const {'1': 'EC_VD_ENGINE_DISCONNECTED', '2': 111},
    const {'1': 'EC_TARGET_STATUS_CHANGED', '2': 112},
    const {'1': 'EC_ACTION_UNEXECUTABLE', '2': 113},
    const {'1': 'EC_ACTION_TASK_FINISHED', '2': 114},
    const {'1': 'EC_FAILED_TOO_MANY_TIMES', '2': 115},
    const {'1': 'EC_FAST_POLL_TASK_STOPPED', '2': 116},
    const {'1': 'EC_NCP_RESET_FAILURE', '2': 117},
    const {'1': 'EC_ASH_NOT_WORKING', '2': 118},
    const {'1': 'EC_ASH_INVALID_FRAME', '2': 119},
    const {'1': 'EC_NCP_UART_WRITE', '2': 120},
    const {'1': 'EC_INVALID_ASH_CRC', '2': 121},
    const {'1': 'EC_INVALID_ASH_LENGTH', '2': 122},
    const {'1': 'EC_EZSP_INVALID_COMMAND', '2': 123},
    const {'1': 'EC_TASK_FINISHED_DIRECTLY', '2': 124},
    const {'1': 'EC_INVALID_ACTION_GROUP_TYPE', '2': 125},
    const {'1': 'EC_CREATE_NULL_ACTION', '2': 126},
    const {'1': 'EC_UPDATE_BINDING_DEVICE', '2': 127},
    const {'1': 'EC_ENTITY_IS_NULL', '2': 128},
    const {'1': 'EC_CONTAINS_DELETED', '2': 129},
    const {'1': 'EC_ILLEGAL_ARGUMENT', '2': 130},
    const {'1': 'EC_INVALID_TASK_STATE', '2': 131},
    const {'1': 'EC_DEVICE_HAS_GONE', '2': 132},
    const {'1': 'EC_ADJUST_TRIP_FAILED_OPENING', '2': 133},
    const {'1': 'EC_ADJUST_TRIP_FAILED_CLOSING', '2': 134},
    const {'1': 'EC_ADJUST_TRIP_FAILED_SETTING', '2': 135},
    const {'1': 'EC_ADJUST_TRIP_FAILED_TIMEOUT', '2': 136},
    const {'1': 'EC_CONTROL_ON_TRIP_ADJUSTING', '2': 137},
    const {'1': 'EC_TRIP_ADJUSTING_NODE_OFFLINE', '2': 138},
    const {'1': 'EC_VDS_SUBSCRIBE_INDEX_TOO_BIG', '2': 139},
    const {'1': 'EC_ADJUST_TRIP_FAILED_REBOOTING', '2': 140},
    const {'1': 'EC_ADJUST_TRIP_EXPECT_FINISHED', '2': 141},
    const {'1': 'EC_ACTION_ENTITY_IS_NULL', '2': 142},
    const {'1': 'EC_WRITE_ATTR_FAILED', '2': 143},
    const {'1': 'EC_SAME_WRITE_ATTR_TASK', '2': 144},
    const {'1': 'EC_PERMIT_JOIN_RESTARTED', '2': 145},
    const {'1': 'EC_PERMIT_JOIN_TASK_CANCELED', '2': 146},
    const {'1': 'EC_ON_OFF_RELAY_DISABLED', '2': 147},
    const {'1': 'EC_EXEC_AUTO_FAILURE', '2': 148},
    const {'1': 'EC_EXEC_AUTO_TIMEOUT', '2': 149},
    const {'1': 'EC_PERMIT_JOIN_DURATION_TOO_LONG', '2': 150},
    const {'1': 'EC_EMBER_NO_BUFFERS', '2': 151},
    const {'1': 'EC_KNOB_ACTION_INVALID_ANGLE', '2': 152},
    const {'1': 'EC_ASH_WRITE_FRAME_FAILURE', '2': 153},
    const {'1': 'EC_ASH_REWRITE_FRAME_FAILURE', '2': 154},
    const {'1': 'EC_ASH_NOT_WORKING_TIMEOUT', '2': 155},
    const {'1': 'EC_INVALID_METHOD', '2': 156},
    const {'1': 'EC_RECORD_CURRENT_VALUE', '2': 157},
    const {'1': 'EC_NO_EXECUTIONS', '2': 158},
    const {'1': 'EC_ACTION_TASK_STOPPED', '2': 159},
    const {'1': 'EC_FAILED_ENABLE_AUTO', '2': 160},
    const {'1': 'EC_NEVER_MATCHED', '2': 161},
    const {'1': 'EC_INVALID_CONFIG_FILE', '2': 162},
    const {'1': 'EC_ENTITY_HAS_NO_ATTR', '2': 163},
    const {'1': 'EC_UPDATE_ACTION_ENTITY', '2': 164},
    const {'1': 'EC_EMPTY_COMPOSED_ACTION', '2': 165},
    const {'1': 'EC_STOP_MOTOR_ON_ADJUSTING', '2': 166},
    const {'1': 'EC_INTERFACE_DISABLED', '2': 167},
    const {'1': 'EC_TIMER_NOT_RUNNING', '2': 168},
    const {'1': 'EC_CONFLICTED_CONDITIONS', '2': 169},
    const {'1': 'EC_NOT_AUTO_TIMER', '2': 170},
    const {'1': 'EC_FAILED_PAUSE_TIMER', '2': 171},
    const {'1': 'EC_FAILED_CONTINUE_TIMER', '2': 172},
    const {'1': 'EC_INVALID_TIMER_STATE', '2': 173},
    const {'1': 'EC_FAILED_CONTROL_TIMER', '2': 174},
  ],
};

const Attribute$json = const {
  '1': 'Attribute',
  '2': const [
    const {'1': 'AttrID', '3': 1, '4': 1, '5': 14, '6': '.xiaoyan.protocol.AttributeID', '10': 'AttrID'},
    const {'1': 'AttrValue', '3': 2, '4': 1, '5': 5, '10': 'AttrValue'},
  ],
};

