part of const_shared;

const double OK_BUTTON_LEFT_PADDING = 25.0;

const int MIN_PASSWORD_LENGTH = 6;
const int BASE_TYPE_UNKNOWN = 0;
const int BASE_TYPE_ROOM = 1;
const int BASE_TYPE_DEVICE = 2;
const int BASE_TYPE_PEOPLE = 3;
const int BASE_TYPE_SYSTEM_DESCRIPTION = 4;
const int BASE_TYPE_FIRMWARE = 5;
const int BASE_TYPE_ACTION_GROUP = 6;
const int BASE_TYPE_AUTOMATION = 7;
const int BASE_TYPE_AUTOMATIONSET = 8;

const int DELETE_STATE_INUSE = 0;
const int DELETE_STATE_STARTED = 1;
const int DELETE_STATE_EXECUTING = 2;
const int DELETE_STATE_COMPLETED = 3;

const int PROFILE_PIR = 0;
const int PROFILE_SMART_PLUG = 1;
const int PROFILE_ON_OFF_LIGHT = 2;
const int PROFILE_DOOR_CONTACT = 3;
const int PROFILE_ON_OFF_SWITCH = 4;
const int PROFILE_WINDOW_CORVERING = 5;
const int PROFILE_YAN_BUTTON = 6;
const int PROFILE_SMART_DIAL = 7;
const int PROFILE_COLOR_LIGHT = 8;
const int PROFILE_HA_ZHH_GATEWAY = 9;
const int PROFILE_HA_ZHH_UNIT_MACHINE = 10;
const int PROFILE_HA_DOOR_LOCK = 11;
const int PROFILE_EXTENDED_COLOR_LIGHT = 12;
const int PROFILE_COLOR_TEMPERATURE_LIGHT = 13;

const int BINDING_TYPE_INVALID = 0;
const int BINDING_TYPE_KEY_PRESS = 1;
const int BINDING_TYPE_OPEN_CLOSE = 2;
const int BINDING_TYPE_PIR = 3;
const int BINDING_TYPE_SMART_DIAL = 4;

const int ATTRIBUTE_DEFAULT_VALUE = -99;

const int ATTRIBUTE_ID_ON_OFF_STATUS = 0;
const int ATTRIBUTE_ID_TOTLE_POWER = 1;
const int ATTRIBUTE_ID_ACTIVE_POWER = 2;
const int ATTRIBUTE_ID_INSERT_EXTRACT_STATUS = 3;
const int ATTRIBUTE_ID_OCCUPANCY = 4;
const int ATTRIBUTE_ID_LUMINANCE = 5;
const int ATTRIBUTE_ID_TEMPERATURE = 6;
const int ATTRIBUTE_ID_BINARY_INPUT_STATUS = 7;
const int ATTRIBUTE_ID_BATTERY_PERCENT = 8;
const int ATTRIBUTE_ID_FIRMWARE_VERSION = 9;
const int ATTRIBUTE_ID_PERMIT_JOIN = 10;
const int ATTRIBUTE_ID_CURTAIN_DIRECTION = 11;
const int ATTRIBUTE_ID_CURTAIN_TARGET_POSITION = 12;
const int ATTRIBUTE_ID_CURTAIN_CURRENT_POSITION = 13;
const int ATTRIBUTE_ID_SUPPORT_OTA = 14;
const int ATTRIBUTE_ID_ALERT_LEVEL = 15;
const int ATTRIBUTE_ID_CURTAIN_STATUS = 16;
const int ATTRIBUTE_ID_CURTAIN_TRIP_CONFIGURED = 17;
const int ATTRIBUTE_ID_CURTAIN_TYPE = 18;
const int ATTRIBUTE_ID_CURTAIN_TRIP_ADJUSTING = 19;
const int ATTRIBUTE_ID_ENTITY_IS_NEW = 20;
const int ATTRIBUTE_ID_JOINED_TIME = 21;
const int ATTRIBUTE_ID_CONNECTED_TIME = 22;
const int ATTRIBUTE_ID_OCCUPANCY_LEFT = 23;
const int ATTRIBUTE_ID_OCCUPANCY_RIGHT = 24;
const int ATTRIBUTE_ID_CONFIG_INDICATOR_LED = 25;
const int ATTRIBUTE_ID_CONFIG_DISABLE_RELAY = 26;
const int ATTRIBUTE_ID_BUTTON_BINDING_TYPE = 27;
const int ATTRIBUTE_ID_LED_LUMNANCE_THRESHOLD = 28;
const int ATTRIBUTE_ID_FIRMWARE_UPGRADING_VERSION = 29;
const int ATTRIBUTE_ID_FIRMWARE_UPGRADING_PERCENT = 30;
const int ATTRIBUTE_ID_ENABLE_KEEP_ON_OFF_STATUS = 31;
const int ATTRIBUTE_ID_FIRMWARE_RECOMMAND_VERSION = 32;
const int ATTRIBUTE_ID_LAST_KNOB_ANGLE = 33;
const int ATTRIBUTE_ID_LAST_KNOB_USED_MS = 34;
const int ATTRIBUTE_ID_AUTO_ENABLED = 35;
const int ATTRIBUTE_ID_AUTO_RENDER_TYPE = 36;
const int ATTRIBUTE_ID_AUTO_SET_ID = 37;
const int ATTRIBUTE_ID_CFG_SW_PURE_INPUT = 38;
const int ATTRIBUTE_ID_CFG_SW_INPUT_MODE = 39;
const int ATTRIBUTE_ID_CFG_SW_POLARITY = 40;
const int ATTRIBUTE_ID_CFG_BUTTON_LED_STATUS = 41;
const int ATTRIBUTE_ID_AUTO_VERSION = 42;
const int ATTRIBUTE_ID_LC_TARGET_LEVEL = 43;
const int ATTRIBUTE_ID_LC_CURRENT_LEVEL = 44;
const int ATTRIBUTE_ID_DISABLE_RELAY_STATUS = 45;
const int ATTRIBUTE_ID_NumOfTimeoutControls = 46;
const int ATTRIBUTE_ID_ZHH_IS_ONLINE = 47;
const int ATTRIBUTE_ID_ZHH_IS_RUNNING = 48;
const int ATTRIBUTE_ID_AC_TARGET_TEMPERATURE = 49;
const int ATTRIBUTE_ID_AC_CURRENT_TEMPERATURE = 50;
const int ATTRIBUTE_ID_AC_FAN_SPEED = 51;
const int ATTRIBUTE_ID_AC_WORK_MODE = 52;
const int ATTRIBUTE_ID_ZHH_ERROR_CODE = 53;
const int ATTRIBUTE_ID_CFG_MUTEXED_INDEX = 54;
const int ATTRIBUTE_ID_CFG_MUTEXED_DELAYMS = 55;
const int ATTRIBUTE_ID_CFG_BUTTON_LED_POLARITY = 56;
const int ATTRIBUTE_ID_CFG_LOOP_HAS_RELAY = 57;
const int ATTRIBUTE_ID_CFG_SELF_BINDING_ID = 58;
const int ATTRIBUTE_ID_AUTOSET_CLASS = 59;
const int ATTRIBUTE_ID_WINDOW_COVERING_MOTOR_TYPE = 60;
const int ATTRIBUTE_ID_COLOR_TEMPERATURE = 61;
const int ATTRIBUTE_ID_COLOR_CURRENT_X = 62;
const int ATTRIBUTE_ID_COLOR_CURRENT_Y = 63;
const int ATTRIBUTE_ID_COLOR_CIE_YXY = 64;
const int ATTRIBUTE_ID_COLOR_CIE_RGB = 65;
const int ATTRIBUTE_ID_ZB_CHANNEL = 66;
const int ATTRIBUTE_ID_CFG_TURNON_ONLY = 67;
const int ATTRIBUTE_ID_CFG_TURNOFF_DELAY_MS = 68;
const int ATTRIBUTE_ID_CFG_SWITCH_DIRECTION = 69;
const int ATTRIBUTE_ID_AUTO_TIMER_STATE = 70;
const int ATTRIBUTE_ID_AUTO_TIMER_REMAINED_TIME_MS = 71;
const int ATTRIBUTE_ID_AUTO_EXEC_STATE = 72;
const int ATTRIBUTE_ID_DOOR_LOCK_STATE = 73;
const int ATTRIBUTE_ID_WINDOW_CONVERING_CONTROL_STATE = 74;
const int ATTRIBUTE_ID_ZB_CHANNEL_UPDATE_STATE = 75;

const int EXPIRE_VRIFICATION_CODE = 600; //(s)
const int EXPIRE_IDENTIFY = 4;

const int LENGTH_VERIFICATION_CODE = 6;

const int ASSOCIATION_TYPE_NONE = 0;
const int ASSOCIATION_TYPE_FROM = 1;
const int ASSOCIATION_TYPE_TO = 2;
const int ASSOCIATION_TYPE_BOTH = 3;

const int ASSOCIATION_ACTION_SHARE = 0;
const int ASSOCIATION_ACTION_REQUEST = 1;
const int ASSOCIATION_ACTION_ACCEPT = 2;
const int ASSOCIATION_ACTION_DECLINE = 3;
const int ASSOCIATION_ACTION_APPROVE = 4;
const int ASSOCIATION_ACTION_REJECT = 5;
const int ASSOCIATION_ACTION_CANCEL_SHARE = 6;
const int ASSOCIATION_ACTION_CANCEL_REQUEST = 7;
const int ASSOCIATION_ACRION_REMOVE = 8;

const int HTTP_STATUS_CODE_QQ_OK = 0;
const int HTTP_STATUS_CODE_OK = 20000;
const int HTTP_STATUS_CODE_INVALID_ID = 40001;
const int HTTP_STATUS_CODE_UNAUTHORIZED = 40100;
const int HTTP_STATUS_CODE_FORBIDDEN = 40300;
const int HTTP_STATUS_CODE_LOCKED = 40301;
const int HTTP_STATUS_CODE_NOT_FOUND = 40400;
const int HTTP_STATUS_CODE_CONFLICT = 40901;
const int HTTP_STATUS_CODE_TOO_OFTEN = 42900;

const int GET_ENTITY_DEVICE = 0;
const int GET_ENTITY_SCENE = 1;
const int GET_ENTITY_AREA = 2;
const int GET_ENTITY_BINDING = 3;
const int GET_ENTITY_SYSTEM = 4;
const int GET_ENTITY_FIRMWARE = 5;
const int GET_ENTITY_AUTOMATION = 6;
const int GET_ENTITY_AUTOMATION_SET = 7;

const int ON_OFF_STATUS_OFF = 0;
const int ON_OFF_STATUS_ON = 1;

const int ACTION_CLOSE = 0;
const int ACTION_OPEN = 1;
const int ACTION_OPEN_OR_CLOSE = 2;

const int LUMINANCE_DEFINED = -1;
const int LUMINANCE_VERY_DARK = 30;
const int LUMINANCE_LITTLE_DARK = 100;
const int LUMINANCE_LIGHT = 300;
const int LUMINANCE_VERY_VERY_LIGHT = 10000;

const int UPGRADE_STATUS_NONE = -1;
const int UPGRADE_STATUS_STARTED = 0;
const int UPGRADE_STATUS_ONGOING = 1;
const int UPGRADE_STATUS_FINISHED = 2;
const int UPGRADE_STATUS_ERROR = 3;

const int CURTAIN_TYPE_NONE = -1;
const int CURTAIN_TYPE_LEFT = 0;
const int CURTAIN_TYPE_RIGHT = 1;
const int CURTAIN_TYPE_DOUBLE = 2;

const int CURTAIN_DIRECTION_UNKNOWN = -1;
const int CURTAIN_DIRECTION_ORIGIN = 0;
const int CURTAIN_DIRECTION_REVERSE = 1;

const int CHANNEL_MQTT = 1;
const int CHANNEL_HOMEKIT = 2;

const EVENT_CHANNEL = const EventChannel('io.xiaoyan.xlive/event_channel');

const String PLATFORM_ANDROID = 'Android';
const String PLATFORM_IOS = 'iOS';

const String APP_ID_QQ = '1106951967';
const String APP_ID_WECHAT = 'wx84882c9bb54b2321';

const String DEFAULT_ROOM = 'area-0000';

const String DEVICE_MODEL_HOME_CENTER = 'TERNCY-GW01';
const String DEVICE_MODEL_LIGHT_SOCKET = 'TERNCY-LS01';
const String DEVICE_MODEL_LIGHT_SOCKET_PHILIPS = 'LCT007';
const String DEVICE_MODEL_SMART_PLUG = 'TERNCY-SP01';
const String DEVICE_MODEL_AWARENESS_SWITCH = 'TERNCY-PP01';
const String DEVICE_MODEL_DOOR_SENSOR = 'TERNCY-DC01';
const String DEVICE_MODEL_CURTAIN = 'TERNCY-CM01';
const String DEVICE_MODEL_SMART_DIAL = 'TERNCY-SD01'; //旋钮
const String DEVICE_MODEL_WALL_SWITCH_S1 = 'TERNCY-WS01-S1';
const String DEVICE_MODEL_WALL_SWITCH_S2 = 'TERNCY-WS01-S2';
const String DEVICE_MODEL_WALL_SWITCH_S3 = 'TERNCY-WS01-S3';
const String DEVICE_MODEL_WALL_SWITCH_S4 = 'TERNCY-WS01-S4';
const String DEVICE_MODEL_WALL_SWITCH_D1 = 'TERNCY-WS01-D1';
const String DEVICE_MODEL_WALL_SWITCH_D2 = 'TERNCY-WS01-D2';
const String DEVICE_MODEL_WALL_SWITCH_D3 = 'TERNCY-WS01-D3';
const String DEVICE_MODEL_WALL_SWITCH_D4 = 'TERNCY-WS01-D4';
const String DEVICE_MODEL_WALL_SWITCH_US1 = 'TERNCY-WS01-US-X1';
const String DEVICE_MODEL_SWITCH_MODULE_D1 = 'TERNCY-SM01-D1';
const String DEVICE_MODEL_SWITCH_MODULE_D2 = 'TERNCY-SM01-D2';
const String DEVICE_MODEL_SWITCH_MODULE_D3 = 'TERNCY-SM01-D3';
const String DEVICE_MODEL_SWITCH_MODULE_D4 = 'TERNCY-SM01-D4';
const String DEVICE_MODEL_SWITCH_MODULE_S1 = 'TERNCY-SM01-S1';
const String DEVICE_MODEL_SWITCH_MODULE_S2 = 'TERNCY-SM01-S2';
const String DEVICE_MODEL_SWITCH_MODULE_S3 = 'TERNCY-SM01-S3';
const String DEVICE_MODEL_SWITCH_MODULE_S4 = 'TERNCY-SM01-S4';
const String DEVICE_MODEL_SMART_LOCK = 'TERNCY-SL01';
const String DEVICE_MODEL_VG = 'TERNCY-VG01';

const String NOTIFICATION_TYPE_SMS = 'sms';
const String NOTIFICATION_TYPE_EMAIL = 'email';
const String NOTIFICATION_TYPE_WECHAT = 'wechat';
const String NOTIFICATION_TYPE_PUSH = 'push';

const String VERIFICATION_CODE_PURPOSE_LOGIN = 'login';
const String VERIFICATION_CODE_PURPOSE_CONFIRM = 'confirm';
const String VERIFICATION_CODE_PURPOSE_RESET_PASSWORD = 'reset_password';

const String VERIFICATION_CODE_TYPE_NUMBER = 'number';
const String VERIFICATION_CODE_TYPE_ALPHABET = 'alphabet';
const String VERIFICATION_CODE_TYPE_ALPHANUM = 'alphanum';

const String ID_TYPE_QQ = 'qq';
const String ID_TYPE_WECHAT = 'wechat';
const String ID_TYPE_WEIBO = 'weibo';
const String ID_TYPE_BASIC = 'basic';
const String ID_TYPE_MOBILE = 'mobile';
const String ID_TYPE_EMAIL = 'email';
const String ID_TYPE_LOCAL = 'local';

const String LOGIN_POLICY_CLOUD = 'CLOUD';
const String LOGIN_POLICY_LOCAL = 'LOCAL';

const String CLOUD_SERVER = 'ws.xiaoyan.io';

const String API_STATUS_CODE = 'status_code';
const String API_MESSAGE = 'message';
const String API_ACCESS_TOKEN = 'access_token';
const String API_USERNAME = 'username';
const String API_ROSTER_USERNAME = 'Username';
const String API_ROSTER = 'roster';
const String API_NICKNAME = 'nickname';
const String API_ROSTER_NICKNAME = 'Nickname';
const String API_TYPE = 'type';
const String API_ROSTER_TYPE = 'Type';
const String API_GROUPS = 'groups';
const String API_ROSTER_GROUPS = 'Groups';
const String API_VERIFICATION_CODE_ID = 'verification_code_id';
const String API_EMAIL = 'email';
const String API_EMAIL_CONFIRMED = 'email_confirmed';
const String API_MOBILE = 'mobile';
const String API_NAME = 'name';
const String API_OPEN_IDS = 'open_ids';
const String API_ID_TYPE = 'id_type';
const String API_OPEN_ID = 'open_id';
const String API_DEVICE_ID = 'device_id';
const String API_NOTIFICATIONS = 'notifications';
const String API_ENABLED = 'enabled';

const String ROSTER_GROUP_GATEWAY = '__gateway__';
const String ROSTER_GROUP_USER = '__user__';

const String ACTION_SHARE = "share";
const String ACTION_REQUEST = "request";
const String ACTION_ACCEPT = "accept";
const String ACTION_DECLINE = "decline";
const String ACTION_APPROVE = "approve";
const String ACTION_REJECT = "reject";
const String ACTION_REMOVE = "remove";
const String ACTION_CANCEL_SHARE = "cancel_share";
const String ACTION_CANCEL_REQUEST = "cancel_request";

const String UPGRADE_POLICY_ALPHA = 'alpha';
const String UPGRADE_POLICY_BETA = 'beta';
const String UPGRADE_POLICY_STABLE = 'stable';

//自动化
const int AUTOMATION_TIME = 0;
const int AUTOMATION_TIMER = 1;
const int AUTOMATION_DEVICE = 2;

const int SETTING_TEM = 0;
const int SETTING_TIME = 1;
const int SETTING_SUN = 2;
const int SETTING_EXCEED = 3;
const int SETTING_SITUATE = 4;
const int SETTING_UNDER = 5;
const int SETTING_POWER = 6;
const int SETTING_DISSIPATION = 7;
const int SETTING_OPEN_CLOSE_STATUES = 8;

const int RADIO_TYPE_PAGE = 0;
const int SUB_COND_PAGE = 1;
const int COND_VALUE_PAGE = 2;

const int TYPE_CONDITION_KEYPRESS = -1;
const int TYPE_CONDITION_BODY = -2;
const int TYPE_CONDITION_TEMPERATURE = -3;
const int TYPE_CONDITION_ILLUMINANCE = -4;
const int TYPE_CONDITION_ACTION = -5;
const int TYPE_CONDITION_ONOFF = -6;
const int TYPE_CONDITION_ACTIVE_POWER = -7;
const int TYPE_CONDITION_TOTAL_POWER = -8;
const int TYPE_CONDITION_CURTIAN_ONOFF = -9;
const int TYPE_CONDITION_CURTAIN_EXERCISE = -10;
const int TYPE_CONDITION_ROTATION_ANGLE = -11;

const int TYPE_CONDITION_CHILD_BODY_LEFT = 2001;
const int TYPE_CONDITION_CHILD_BODY_RIGHT = 2002;
const int TYPE_CONDITION_CHILD_BODY_DOUBLE = 2003;
const int TYPE_CONDITION_CHILD_ROTATION_TYPE = 2004;
const int TYPE_CONDITION_CHILD_RATATION_RANGE = 2005;

const int CONDITION_DEVICE_TYPE_PIR = 0;
const int CONDITION_DEVICE_TYPE_PLUG = 1;
const int CONDITION_DEVICE_TYPE_LIGHT = 2;
const int CONDITION_DEVICE_TYPE_SENSOR = 3;
const int CONDITION_DEVICE_TYPE_UI = 4;
const int CONDITION_DEVICE_TYPE_CURTAIN = 5;
const int CONDITION_DEVICE_TYPE_BUTTON = 6;
const int CONDITION_DEVICE_TYPE_SMART_DIAL = 7;
const int CONDITION_DEVICE_TYPE_UN = 8;

const int HAS_PEOPLE_ACTION = 0;
const int NO_PEOPLE_ACTION = 1;
const int DIRECTION_LEFT_TO_RIGHT = 2;
const int DIRECTION_RIGHT_TO_LEFT = 3;

const int AUTO_CLICK = 0;
const int AUTO_DB_CLICK = 1;
const int AUTO_OPEN = 2;
const int AUTO_CLOSE = 3;
const int AUTO_OPENING = 4;
const int AUTO_CLOSEING = 5;
const int AUTO_OPENING_OR_CLOSEING = 6;
const int AUTO_STACK = 7;
const int AUTO_LONG_PRESS = 8;
const int AUTO_LEFT_ROTATE = 9;
const int AUTO_RIGHT_ROTATE = 10;
const int AUTO_LEFT_RO_RIGHT_ROTATE = 11;

const int TYPE_TRAVELING_SPEED = 0;
const int TYPE_HAS_PEOPLE_ACTION = 1;
const int TYPE_DIRECTION_LEFT_TO_RIGHT = 2;
const int TYPE_DIRECTION_RIGHT_TO_LEFT = 3;

const int LOCAL_TYPE_TIME = 0;
const int LOCAL_TYPE_TEM = 1;
const int LOCAL_TYPE_SUN = 2;
const int LOCAL_TYPE_PERCENT = 3;
const int LOCAL_TYPE_POWER = 4;

const int COND_COUNT = 1;

const int CAN_CHANGE_CHANNEL = 20610;

const int AIR_CONDITION_SPEED_LOW = 4;
const int AIR_CONDITION_SPEED_INTERMEDIATE = 2;
const int AIR_CONDITION_SPEED_QUICK = 1;

const int MODE_HEATING = 8; //制热
const int MODE_REFRIGERATION = 1; //制冷
const int MODE_DEHUMIDIFICATION = 2; //除湿
const int MODE_VENTILATE = 4; //通风
