//
//  EventType.m
//  Runner
//
//  Created by litao on 2018/11/26.
//  Copyright © 2018年 The Chromium Authors. All rights reserved.
//

#import "EventType.h"

@implementation EventType

int const HOME_MANAGER_DID_UPDATE_HOMES = 0x2001;
int const HOME_MANAGER_DID_UPDATE_PRIMARY_HOME = 0x2002;
int const HOME_MANAGER_DID_ADD_HOME = 0x2003;
int const HOME_MANAEGR_DID_REMOVE_HOME = 0x2004;

int const HOME_DID_UPDATE_NAME = 0x0001;
int const HOME_DID_UPDATE_ACCESSORY_CONTROL_FOR_CURRENT_USER = 0x0002;
int const HOME_DID_ADD_ACCESSORY = 0x0003;
int const HOME_DID_REMOVE_ACCESORY = 0x0004;
int const HOME_DID_ADD_USER = 0x0005;
int const HOME_DID_REMOVE_USER = 0x0006;
int const HOME_DID_UPDATE_ROOM_FOR_ACCESSORY = 0x0007;
int const HOME_DID_ADD_ROOM = 0x0008;
int const HOME_DID_REMOVE_ROOM = 0x0009;
int const HOME_DID_UPDATE_NAME_FOR_ROOM = 0x000A;
int const HOME_DID_ADD_ZONE = 0x000B;
int const HOME_DID_REMOVE_ZONE = 0x000C;
int const HOME_DID_UPDATE_NAME_FOR_ZONE = 0x000D;
int const HOME_DID_ADD_ROOM_TO_ZONE = 0x000E;
int const HOME_DID_REMOVE_ROOM_FROM_ZONE = 0x000F;
int const HOME_DID_ADD_SERVICE_GROUP = 0x0010;
int const HOME_DID_REMOVE_SERVICE_GROUP = 0x0011;
int const HOME_DID_UPDATE_NAME_FOR_SERVICE_GROUP = 0x0012;
int const HOME_DID_ADD_SERVICE_TO_SERVICE_GROUP = 0x0013;
int const HOME_DID_REMOVE_SERVICE_FROM_SERVICE_GROUP = 0x0014;
int const HOME_DID_ADD_ACTION_SET = 0x0015;
int const HOME_DID_REMOVE_ACTION_SET = 0x0016;
int const HOME_DID_UPDATE_NAME_FOR_ACTION_SET = 0x0017;
int const HOME_DID_UPDATE_ACTIONS_FOR_ACTION_SET = 0x0018;
int const HOME_DID_ADD_TRIGGER = 0x0019;
int const HOME_DID_REMOVE_TRIGGER = 0x001A;
int const HOME_DID_UPDATE_NAME_FOR_TRIGGER = 0x001B;
int const HOME_DID_UPDATE_TRIGGER = 0x001C;
int const HOME_DID_UNBLOCK_ACCESSORY = 0x001D;
int const HOME_DID_ENCOUNTER_ERROR_FOR_ACCESSORY = 0x001E;
int const HOME_DID_UPDATE_HOME_HUB_STATE = 0x001F;

int const ACCESSORY_DID_UPDATE_NAME = 0x1001;
int const ACCESSORY_DID_UPDATE_NAME_FOR_SERVICE = 0x1002;
int const ACCESSORY_DID_UPDATE_ASSOCIATED_SERVICE_TYPE_FOR_SERVICE = 0x1003;
int const ACCESSORY_DID_UPDATE_SERVICES = 0x1004;
int const ACCESSORY_DID_ADD_PROFILE = 0x1005;
int const ACCESSORY_DID_REMOVE_PROFILE = 0x1006;
int const ACCESSORY_DID_UPDATE_REACHABILITY = 0x1007;
int const ACCESSORY_SERVICE_DID_UPDATE_VALUE_FOR_CHARACTERISTIC = 0x1008;
int const ACCESSORY_DID_UPDATE_FIRMWARE_VERSION = 0x1009;

int const ACCESSORY_AVAILABLE_STATUS_CHANGED = 0x5001;
int const ACCESSORY_UPDATING_STATUS_CHANGED = 0x5002;
int const CHARACTERISTIC_VALUE_CHANGED = 0x5003;
int const ADD_ACTION_RESPONSE = 0x5004;
int const REMOVE_ACTION_RESPONSE = 0x5005;
int const UPDATE_ACTION_RESPONSE = 0x5006;

int const LOCAL_SERVICE_DID_FOUND = 0x3001;
int const LOCAL_SERVICE_DID_LOST = 0x3002;

int const NO_ACCESS_TO_CAMERA = 0x4001;

@end
